### ISSUE TITLE
Cannot load world with mod installed.

### ISSUE THREAD

**Issue by Moobien** [HaydenBelanger/assemblylinemachines#23]
Mod Version: assemblylinemachines-1.18-1.3.2
Game Version: 1.18.1
Forge Version: 39.0.7

I installed the mod to give it a try and am getting the following error on world load of an existing world and a new created world.

Latest.log included. https://gist.github.com/Moobien/9e0b758794ae1fcffa7c1f17789d0c64

"Errors in currently selected datapacks prevented the world from loading"

Removing the mod allows correct world loading.

**Comment by HaydenBelanger** [comment]
Hi, I believe this would be a bug with ToolUpgrades-1.18-3.0.0, as they are adding an invalid reference to tag `forge:rods`, and my mod uses this reference, and since ToolUpgrades disables the tag during loading due to an invalid reference, it crashes when it gets to the part where it loads my recipes.
I would send this to the developer of ToolUpgrades.
