### ISSUE TITLE
Take too long to log in

### ISSUE THREAD

**Issue by MRDen3000YT** [HaydenBelanger/assemblylinemachines#50]
Hello! I use your mod on my forge server, and i cant join with this mod.

My server hasn't  any errors. 

My client has lag on [Render thread/INFO] [GameData/REGISTRIES]: Injecting existing registry data into this CLIENT instance

And it takes about 4 minutes to render it, then server kick me for reason: It took to long to log in

How can i fix this?

**Comment by MRDen3000YT** [comment]
Version: 1.16.5

**Comment by dantistruct** [comment]
Having the same issue here. If I try to connect locally it will go through, but when someone remote connects it won't work. I'm guessing it's a timeout issue from the server taking to respond and kicking the user:

[21:51:07] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: Disconnecting com.mojang.authlib.GameProfile@5ebba904[id=03c2296c-2b96-456f-a6c0-9ef0d4de814b,name=mBonBon88,properties={textures=[com.mojang.authlib.properties.Property@533fde94]},legacy=false] (/47.38.246.131:62467): Took too long to log in

I am playing on 1.18.2, I tried removing all other mods and only have this mod running. Same thing.

**Comment by dantistruct** [comment]
Is this still supported?

**Comment by Daihok41** [comment]
I am getting same issue on 1.18.2

**Comment by HaydenBelanger** [comment]
@Daihok41 @dantistruct @MRDen3000YT HI all, this is still definitely supported, unfortunately I'm very limited on free time at the moment and am 90% of the way through a huge feature update. I will try my best to get out a quick patch for this ASAP. Thank you for being patient!

**Comment by dantistruct** [comment]
Okay I'll check the recommendation you have mentioned in the previous issue tracker, and see if it works. I'll update here with my results! Thank you.

**Comment by dantistruct** [comment]
@HaydenBelanger Hey yeah I tried, your fix but to no avail.

**Comment by HaydenBelanger** [comment]
Hi all,

Unfortunately, I just can't reproduce this issue, nor can my friends/testers, and it seems like it's a pretty narrow field of effect. We've tried with the server and client on multiple different PCs and all times I'm able to connect just fine. As a result, I can only recommend general troubleshooting steps:
- Increase/decrease RAM on both server/client (test multiple configurations: if one player is having problems, make sure their RAM is changed to see if that lets them get in)
- Make sure you are using the latest version of Forge for whatever version you are having the issue with.
- Try using [Adoptium JDK](https://adoptium.net/installation/) instead of the Minecraft default JRE. The latest available right now is 17.0.2+8. Also, try using the OpenJ9 version instead of the Hotspot version.

Again, I'm sorry I can't be of more help; this seems like a specific install-related issue.

**Comment by HaydenBelanger** [comment]
Hi all,

Another possible debug step, try replacing JEI (If you have it installed) with [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) on both the client and server. As I understand, JEI in recent versions causes a large amount of hang with custom recipe types during initialization when the client first connects to the server and can just barely cause too much processing (on the client) to not allow a connection and to return the "took too long to log in" bug. REI works with all JEI custom recipe types.
